# This file is auto-generated by the Rails db:migrate task.
# Instead of editing this file, please submit a migration to add any changes.

ActiveRecord::Schema[7.2].define(version: 2026_04_24_145702) do
  create_table "shared_videos", force: :cascade do |t|
    t.bigint "user_id", null: false
    t.string "youtube_url", null: false
    t.string "title", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["user_id"], name: "index_shared_videos_on_user_id"
  end

  create_table "users", force: :cascade do |t|
    t.string "email", null: false
    t.string "password_digest", null: false
    t.string "name", null: false
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.index ["email"], name: "index_users_on_email", unique: true
  end

  add_foreign_key "shared_videos", "users"
end
